### PR TITLE
Site for Github Pages

### PR DESCRIPTION
**Pull request by IM-TECHNO**
This PR solves #12 for Github Pages

### CODE REVIEW

**Comment by freyxfi** [comment]
Thanks for the pull request! I noticed that the index.html is placed in the website directory. However, for GitHub Pages to serve the file directly at the root URL (e.g., https://username.github.io/repo), the index.html file needs to be in the root directory of the repository.

Could you move the index.html to the root, or I can update the project settings to account for the subdirectory if that's the intended structure?"

This keeps the communication clear and allows for flexibility depending on how the site structure was intended

**Comment by IM-TECHNO** [comment]
Thanks for pointing that out. The reason I placed the index.html in the website directory is to keep the project structure organized. This will make future updates and enhancements easier to manage, especially as the site grows.

If you'd prefer, I can move the files to the root directory

**Comment by freyxfi** [comment]
Ah, sure! That’s good project structure planning. However, we should mention that in the README since I was considering adding an .htaccess file to manage redirects, which could simplify access. It might get a bit more complex since my GitHub Pages is already using the Chirpy theme, but no worries I’ll merge it for now. If anything comes up, I’ll let you know or work on it myself.

Feel free to connect on Discord: xfi1337.
Cheers,
Frey

**Comment by IM-TECHNO** [comment]
Glad to hear you’re onboard with the structure. Definitely, adding a note to the README about the directory setup and any potential redirects via .htaccess is a great idea. That should help keep everything clear as the project evolves.


Gave you a req! Have a good day!

**Pull request merged**
