### PR TITLE
Update bug_recon.py

### PR DESCRIPTION
**Pull request by l00pzwastaken**
added flags, threading proper output saving features and logo

### CODE REVIEW

**Comment by l00pzwastaken** [comment]
@freyxfi  check :) and marge into test for now

**Comment by freyxfi** [comment]
Hi @l00pzwastaken thanks for contributing well I am outside right now I will review and merge it as soon I get back. And Yes I have got your message on discord. 
cheers

**Comment by freyxfi** [comment]
Yeah seems fine but the crawler also extracting the emails

**Comment by l00pzwastaken** [comment]
@freyxfi  will fix  the email thing :)

**Pull request merged**
